name: Test Build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'

      - name: Chmod
        run: chmod +x gradlew

      - name: Build and test
        run: ./gradlew build
